on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [0, 1]
    steps:
    - run: exit ${{ matrix.a }}

  check:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result != 'success' }}
        run: exit 1
